# CS6580 - Sprint 1

## Team Grapefruit

*Weber State University*

In [1]:
# Imports and global definitions

import pandas as pd
import numpy as np
import os

interim_path = "https://connorwtech.com/resources/downloads/interim/"
processed_path = "https://connorwtech.com/resources/downloads/processed/"

## Question 1: Data Loading and Exploration

In [2]:
df_A = pd.read_csv(processed_path + "df_A.csv")
df_B = pd.read_csv(processed_path + "df_B.csv")

In [3]:
print("df_A shape:", df_A.shape)
display(df_A.head())
display(df_A.info())

df_A shape: (514, 31)

,fips,TOT_POP_1519_C,TOT_POP_2024_C,TOT_POP_2529_C,TOT_POP_3034_C,TOT_POP_3539_C,TOT_FEMALE_1519_C,TOT_FEMALE_2024_C,TOT_FEMALE_2529_C,TOT_FEMALE_3034_C,...,H_FEMALE_1519_C,H_FEMALE_2024_C,H_FEMALE_2529_C,H_FEMALE_3034_C,H_FEMALE_3539_C,dem2010_P,birth_rate_2010_N,births_2010_N,birth_rate_2020_N,births_2020_N
0,1003,11600,9449,10247,10709,11558,5670,4656,5064,5392,...,263,315,345,327,263,0.227007,11.89,2167.0,10.00,2292.0
1,1015,8607,9022,7601,7186,7232,4264,4548,3890,3669,...,125,211,170,167,109,0.333515,11.12,1318.0,11.12,1262.0
2,1055,7224,6070,6022,6024,6931,3456,3006,3057,3129,...,138,153,142,125,92,0.301366,11.84,1236.0,11.44,1171.0
3,1073,44662,46405,48533,44764,42291,22094,24107,25309,23312,...,743,1170,1347,1145,864,0.523792,13.51,8894.0,12.10,7929.0
4,1081,13185,21095,10675,8672,8721,6604,10227,5245,4443,...,199,289,200,171,140,0.394529,10.92,1532.0,11.04,1842.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fips               514 non-null    int64
 1   TOT_POP_1519_C     514 non-null    int64
 2   TOT_POP_2024_C     514 non-null    int64
 3   TOT_POP_2529_C     514 non-null    int64
 4   TOT_POP_3034_C     514 non-null    int64
 5   TOT_POP_3539_C     514 non-null    int64
 6   TOT_FEMALE_1519_C  514 non-null    int64
 7   TOT_FEMALE_2024_C  514 non-null    int64
 8   TOT_FEMALE_2529_C  514 non-null    int64
 9   TOT_FEMALE_3034_C  514 non-null    int64
 10  TOT_FEMALE_3539_C  514 non-null    int64
 11  WA_FEMALE_1519_C   514 non-null    int64
 12  WA_FEMALE_2024_C   514 non-null    int64
 13  WA_FEMALE_2529_C   514 non-null    int64
 14  WA_FEMALE_3034_C   514 non-null    int64
 15  WA_FEMALE_3539_C   514 non-null    int64
 16  BA_FEMALE_1519_C   514 non-null    int64
 17  BA_FEMALE_2024_C   514 non-null    int64
 18  BA_FEMALE_2529_C   514 non-null    int64
 19  BA_FEMALE_3034_C   514 non-null    int64
 20  BA_FEMALE_3539_C   514 non-null    int64
 21  H_FEMALE_1519_C    514 non-null    int64
 22  H_FEMALE_2024_C    514 non-null    int64
 23  H_FEMALE_2529_C    514 non-null    int64
 24  H_FEMALE_3034_C    514 non-null    int64
 25  H_FEMALE_3539_C    514 non-null    int64
 26  dem2010_P          514 non-null    float64
 27  birth_rate_2010_N  514 non-null    float64
 28  births_2010_N      514 non-null    float64
 29  birth_rate_2020_N  514 non-null    float64
 30  births_2020_N      514 non-null    float64
dtypes: float64(5), int64(26)
memory usage: 124.6 KB

None

In [4]:
print("df_B shape:", df_B.shape)
display(df_B.head())
display(df_B.info())

df_B shape: (514, 29)

,fips,TOT_POP_1519_C,TOT_POP_2024_C,TOT_POP_2529_C,TOT_POP_3034_C,TOT_POP_3539_C,TOT_FEMALE_1519_C,TOT_FEMALE_2024_C,TOT_FEMALE_2529_C,TOT_FEMALE_3034_C,...,BA_FEMALE_3034_C,BA_FEMALE_3539_C,H_FEMALE_1519_C,H_FEMALE_2024_C,H_FEMALE_2529_C,H_FEMALE_3034_C,H_FEMALE_3539_C,dem2020_P,birth_rate_2020_N,births_2020_N
0,1003,13865,11342,12438,13110,13976,6893,5624,6231,6697,...,714,696,512,388,330,440,447,0.224090,10.00,2292.0
1,1015,8613,8189,7566,7268,6977,4273,4082,3836,3677,...,854,797,260,176,134,188,164,0.298452,11.12,1262.0
2,1055,6132,5925,6483,5997,6169,2979,2919,3294,3152,...,595,561,222,174,173,186,151,0.242352,11.44,1171.0
3,1073,42319,41675,48750,48392,44968,21093,21528,25304,25316,...,11556,10986,1358,1192,1183,1236,1142,0.557585,12.10,7929.0
4,1081,14437,22170,12568,11349,11139,7228,10564,6283,5782,...,1535,1451,417,385,284,368,280,0.389928,11.04,1842.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fips               514 non-null    int64
 1   TOT_POP_1519_C     514 non-null    int64
 2   TOT_POP_2024_C     514 non-null    int64
 3   TOT_POP_2529_C     514 non-null    int64
 4   TOT_POP_3034_C     514 non-null    int64
 5   TOT_POP_3539_C     514 non-null    int64
 6   TOT_FEMALE_1519_C  514 non-null    int64
 7   TOT_FEMALE_2024_C  514 non-null    int64
 8   TOT_FEMALE_2529_C  514 non-null    int64
 9   TOT_FEMALE_3034_C  514 non-null    int64
 10  TOT_FEMALE_3539_C  514 non-null    int64
 11  WA_FEMALE_1519_C   514 non-null    int64
 12  WA_FEMALE_2024_C   514 non-null    int64
 13  WA_FEMALE_2529_C   514 non-null    int64
 14  WA_FEMALE_3034_C   514 non-null    int64
 15  WA_FEMALE_3539_C   514 non-null    int64
 16  BA_FEMALE_1519_C   514 non-null    int64
 17  BA_FEMALE_2024_C   514 non-null    int64
 18  BA_FEMALE_2529_C   514 non-null    int64
 19  BA_FEMALE_3034_C   514 non-null    int64
 20  BA_FEMALE_3539_C   514 non-null    int64
 21  H_FEMALE_1519_C    514 non-null    int64
 22  H_FEMALE_2024_C    514 non-null    int64
 23  H_FEMALE_2529_C    514 non-null    int64
 24  H_FEMALE_3034_C    514 non-null    int64
 25  H_FEMALE_3539_C    514 non-null    int64
 26  dem2020_P          514 non-null    float64
 27  birth_rate_2020_N  514 non-null    float64
 28  births_2020_N      514 non-null    float64
dtypes: float64(3), int64(26)
memory usage: 116.6 KB

None